import {
  Alone,
  AnimatedSeries,
  Avenger,
  BlackAdam,
  BlackWidow,
  BlackWidowMovie,
  Buckey,
  Danav,
  DeadPool,
  DeadPool2,
  DeadPool3,
  Force,
  Frozen,
  GardianofGalaxyVol1,
  GardianofGalaxyVol2,
  GardianofGalaxyVol3,
  HellBoy,
  InfinityWar,
  InterStellar,
  JurasiccPark as JurassicPark,
  JustisLegue as JusticeLeague,
  KingKong,
  MsMarwel,
  Solder,
  SpiderMan,
  Transformer,
  TugOfWar,
  Vampire,
  Venom,
  War,
  WitchHunter,
  WonderWomen,
  WonderWomen2,
  XMen,
} from "../assets/movies";

export const MovieData: MovieRecordType = {
  XMen: {
    title: "XMen",
    description: "2014 | Action | Fiction",
    isFavorite: false,
    isTrending: true,
    image: XMen,
  },
  Avenger: {
    title: "Avenger",
    description: "2014 | Action | Fiction",
    image: Avenger,
    isFavorite: false,
    isTrending: true,
  },
  BlackAdams: {
    title: "BlackAdams",
    description: "2022 | Action | Fiction",
    image: BlackAdam,
    isFavorite: false,
    isTrending: true,
  },
  WonderWomen: {
    title: "WonderWomen | Action | Fiction",
    description: "2016",
    image: WonderWomen,
    isFavorite: false,
    isTrending: false,
  },
  WonderWomen2: {
    title: "",
    description: "2018 | Action | Fiction",
    image: WonderWomen2,
    isFavorite: false,
    isTrending: false,
  },
  Alone: {
    title: "Alone",
    description: "2019 | Thriller",
    image: Alone,
    isFavorite: false,
    isTrending: false,
  },
  AnimatedSeries: {
    title: "Animated Series",
    description: "2019 | Animated",
    image: AnimatedSeries,
    isFavorite: false,
    isTrending: false,
  },
  BlackWidow: {
    title: "BlackWidow",
    description: "2022 | Action | Fiction",
    image: BlackWidow,
    isFavorite: false,
    isTrending: false,
  },
  BlackWidowMovie: {
    title: "BlackWidowMovie",
    description: "2023 | Action | Fiction",
    image: BlackWidowMovie,
    isFavorite: false,
    isTrending: false,
  },
  Buckey: {
    title: "Buckey",
    description: "2019 | Action | Fiction",
    image: Buckey,
    isFavorite: false,
    isTrending: false,
  },
  Danav: {
    title: "Danav",
    description: "2023 | Action | Horror | Fiction",
    image: Danav,
    isFavorite: false,
    isTrending: false,
  },
  DeadPool: {
    title: "DeadPool",
    description: "2015 | Action | Fiction",
    image: DeadPool,
    isFavorite: false,
    isTrending: true,
  },
  DeadPool2: {
    title: "DeadPool2",
    description: "2017 | Action | Fiction",
    image: DeadPool2,
    isFavorite: false,
    isTrending: true,
  },
  DeadPool3: {
    title: "DeadPool3",
    description: "2019 | Action | Fiction",
    image: DeadPool3,
    isFavorite: false,
    isTrending: true,
  },
  Force: {
    title: "Force",
    description: "2018 | Action",
    image: Force,
    isFavorite: false,
    isTrending: false,
  },
  Frozen: {
    title: "Frozen",
    description: "2021 | Animated",
    image: Frozen,
    isFavorite: false,
    isTrending: false,
  },
  GardianofGalaxyVol1: {
    title: "Galaxy of Galaxy Vol",
    description: "2011 | Action | Fiction",
    image: GardianofGalaxyVol1,
    isFavorite: false,
    isTrending: true,
  },
  GardianofGalaxyVol2: {
    title: "Galaxy of Galaxy Vol",
    description: "2011 | Action | Fiction",
    image: GardianofGalaxyVol2,
    isFavorite: false,
    isTrending: true,
  },
  GardianofGalaxyVol3: {
    title: "Galaxy of Galaxy Vol",
    description: "2011 | Action | Fiction",
    image: GardianofGalaxyVol3,
    isFavorite: false,
    isTrending: true,
  },
  HellBoy: {
    title: "Hell Boy",
    description: "Action | Fiction",
    image: HellBoy,
    isFavorite: false,
    isTrending: true,
  },
  InfinityWar: {
    title: "Infinity War",
    description: "2020",
    image: InfinityWar,
    isFavorite: false,
    isTrending: true,
  },
  InterStellar: {
    title: "InterStellar",
    description: "2018 | Adventure",
    image: InterStellar,
    isFavorite: false,
    isTrending: true,
  },
  JurassicPark: {
    title: "",
    description: "",
    image: JurassicPark,
    isFavorite: false,
    isTrending: false,
  },
  JusticeLeague: {
    title: "Justice League",
    description: "",
    image: JusticeLeague,
    isFavorite: false,
    isTrending: true,
  },
  KingKong: {
    title: "King KONG",
    description: "2018 | Adventure",
    image: KingKong,
    isFavorite: false,
    isTrending: true,
  },
  MsMarwel: {
    title: "Ms Marwel",
    description: "2018 | Action",
    image: MsMarwel,
    isFavorite: false,
    isTrending: true,
  },
  Soldier: {
    title: "King KONG",
    description: "2018 | Action",
    image: Solder,
    isFavorite: false,
    isTrending: true,
  },
  SpiderMan: {
    title: "Spiderman",
    description: "2018 | Action | Fiction",
    image: SpiderMan,
    isFavorite: false,
    isTrending: true,
  },
  Transformer: {
    title: "Transformer",
    description: "2019 | Action | Fiction",
    image: Transformer,
    isFavorite: false,
    isTrending: true,
  },
  TugOfWar: {
    title: "Tug Of War",
    description: "2017 | Action",
    image: TugOfWar,
    isFavorite: false,
    isTrending: false,
  },
  Vampire: {
    title: "Vampire",
    description: "2017 | Action",
    image: Vampire,
    isFavorite: false,
    isTrending: false,
  },
  Venom: {
    title: "Venom",
    description: "2017 | Action",
    image: Venom,
    isFavorite: false,
    isTrending: true,
  },
  War: {
    title: "War",
    description: "2022 | Action",
    image: War,
    isFavorite: false,
    isTrending: false,
  },
  WitchHunter: {
    title: "Witch Hunter",
    description: "2017 | Action",
    image: WitchHunter,
    isFavorite: false,
    isTrending: false,
  },
};
